// Generated by scripts/generate-dock-thread-card-contract.mjs.
// Source contract: contract/dock/dock-thread-card.schema.json

import Foundation

public enum ThreadCardStreamView: String, Codable, Equatable, Sendable {
    case dock
    case archive
}

public enum DockStreamKind: String, Codable, Equatable, Sendable {
    case snapshot
    case delta
    case heartbeat
}

public enum DockThreadCardStatus: Equatable, Sendable {
    case running
    case needsInput
    case needsApproval
    case idle
    case error
    case dormant
    case unknown

    public var rawValue: String {
        switch self {
        case .running:
            return "running"
        case .needsInput:
            return "needsInput"
        case .needsApproval:
            return "needsApproval"
        case .idle:
            return "idle"
        case .error:
            return "error"
        case .dormant:
            return "dormant"
        case .unknown:
            return "unknown"
        }
    }
}

extension DockThreadCardStatus: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        switch try container.decode(String.self) {
        case "running":
            self = .running
        case "needsInput":
            self = .needsInput
        case "needsApproval":
            self = .needsApproval
        case "idle":
            self = .idle
        case "error":
            self = .error
        case "dormant":
            self = .dormant
        default:
            self = .unknown
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public enum DockStreamFreshnessStatus: Equatable, Sendable {
    case unknown
    case fresh
    case stale
    case offline
    case error

    public var rawValue: String {
        switch self {
        case .unknown:
            return "unknown"
        case .fresh:
            return "fresh"
        case .stale:
            return "stale"
        case .offline:
            return "offline"
        case .error:
            return "error"
        }
    }
}

extension DockStreamFreshnessStatus: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        switch try container.decode(String.self) {
        case "fresh":
            self = .fresh
        case "stale":
            self = .stale
        case "offline":
            self = .offline
        case "error":
            self = .error
        default:
            self = .unknown
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct DockStreamFreshnessDTO: Codable, Equatable, Sendable {
    public let status: DockStreamFreshnessStatus
    public let lastAttemptAt: String?
    public let lastSyncAt: String?
    public let lastError: String?

    public init(
        status: DockStreamFreshnessStatus,
        lastAttemptAt: String? = nil,
        lastSyncAt: String? = nil,
        lastError: String? = nil
    ) {
        self.status = status
        self.lastAttemptAt = lastAttemptAt
        self.lastSyncAt = lastSyncAt
        self.lastError = lastError
    }
}

public struct DockStreamHostDTO: Codable, Equatable, Sendable {
    public let id: String
    public let logicalHostID: String
    public let displayName: String?
    public let endpoint: String?

    public init(
        id: String,
        logicalHostID: String,
        displayName: String? = nil,
        endpoint: String? = nil
    ) {
        self.id = id
        self.logicalHostID = logicalHostID
        self.displayName = displayName
        self.endpoint = endpoint
    }
}

public enum DockThreadCardSourceKind: Equatable, Sendable {
    case human
    case automation
    case unknown

    public var rawValue: String {
        switch self {
        case .human:
            return "human"
        case .automation:
            return "automation"
        case .unknown:
            return "unknown"
        }
    }
}

extension DockThreadCardSourceKind: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        switch try container.decode(String.self) {
        case "human":
            self = .human
        case "automation":
            self = .automation
        default:
            self = .unknown
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public enum DockThreadCardLane: Equatable, Sendable {
    case human
    case agent
    case unknown

    public var rawValue: String {
        switch self {
        case .human:
            return "human"
        case .agent:
            return "agent"
        case .unknown:
            return "unknown"
        }
    }
}

extension DockThreadCardLane: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        switch try container.decode(String.self) {
        case "human":
            self = .human
        case "agent":
            self = .agent
        default:
            self = .unknown
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public enum DockThreadCardArchiveState: Equatable, Sendable {
    case active
    case archived
    case unknown

    public var rawValue: String {
        switch self {
        case .active:
            return "active"
        case .archived:
            return "archived"
        case .unknown:
            return "unknown"
        }
    }
}

extension DockThreadCardArchiveState: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        switch try container.decode(String.self) {
        case "active":
            self = .active
        case "archived":
            self = .archived
        default:
            self = .unknown
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public enum DockThreadCardCompleteness: Equatable, Sendable {
    case complete
    case partial
    case unknown

    public var rawValue: String {
        switch self {
        case .complete:
            return "complete"
        case .partial:
            return "partial"
        case .unknown:
            return "unknown"
        }
    }
}

extension DockThreadCardCompleteness: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        switch try container.decode(String.self) {
        case "complete":
            self = .complete
        case "partial":
            self = .partial
        default:
            self = .unknown
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct DockThreadCardDTO: Codable, Equatable, Sendable {
    public let id: String
    public let logicalHostID: String
    public let threadID: String
    public let backendSessionID: String
    public let hostDisplayName: String
    public let hostEndpoint: String?
    public let orderKey: String
    public let activityAt: String
    public let activityAtMs: Int64?
    public let displaySummary: String
    public let title: String
    public let status: DockThreadCardStatus
    public let sourceKind: DockThreadCardSourceKind
    public let lane: DockThreadCardLane
    public let archiveState: DockThreadCardArchiveState
    public let freshness: DockStreamFreshnessStatus
    public let completeness: DockThreadCardCompleteness
    public let repository: String?
    public let workingDirectory: String?
    public let branch: String?
    public let summarySource: String?

    public init(
        id: String,
        logicalHostID: String,
        threadID: String,
        backendSessionID: String,
        hostDisplayName: String,
        hostEndpoint: String? = nil,
        orderKey: String,
        activityAt: String,
        activityAtMs: Int64? = nil,
        displaySummary: String,
        title: String,
        status: DockThreadCardStatus,
        sourceKind: DockThreadCardSourceKind,
        lane: DockThreadCardLane,
        archiveState: DockThreadCardArchiveState,
        freshness: DockStreamFreshnessStatus,
        completeness: DockThreadCardCompleteness,
        repository: String? = nil,
        workingDirectory: String? = nil,
        branch: String? = nil,
        summarySource: String? = nil
    ) {
        self.id = id
        self.logicalHostID = logicalHostID
        self.threadID = threadID
        self.backendSessionID = backendSessionID
        self.hostDisplayName = hostDisplayName
        self.hostEndpoint = hostEndpoint
        self.orderKey = orderKey
        self.activityAt = activityAt
        self.activityAtMs = activityAtMs
        self.displaySummary = displaySummary
        self.title = title
        self.status = status
        self.sourceKind = sourceKind
        self.lane = lane
        self.archiveState = archiveState
        self.freshness = freshness
        self.completeness = completeness
        self.repository = repository
        self.workingDirectory = workingDirectory
        self.branch = branch
        self.summarySource = summarySource
    }
}

public struct DockStreamWindowDTO: Codable, Equatable, Sendable {
    public let offset: Int
    public let limit: Int
    public let rowCount: Int
    public let nextOffset: Int?

    public init(
        offset: Int,
        limit: Int,
        rowCount: Int,
        nextOffset: Int? = nil
    ) {
        self.offset = offset
        self.limit = limit
        self.rowCount = rowCount
        self.nextOffset = nextOffset
    }
}

public struct ThreadCardStreamUpdateDTO: Codable, Equatable, Sendable {
    public let kind: DockStreamKind
    public let schemaVersion: Int?
    public let view: ThreadCardStreamView?
    public let complete: Bool?
    public let totalRows: Int?
    public let window: DockStreamWindowDTO?
    public let stateGeneration: Int64?
    public let epoch: String
    public let baseSeq: Int64?
    public let seq: Int64
    public let asOf: String?
    public let freshness: DockStreamFreshnessDTO?
    public let hosts: [DockStreamHostDTO]?
    public let cards: [DockThreadCardDTO]?
    public let upsertHosts: [DockStreamHostDTO]?
    public let upsertCards: [DockThreadCardDTO]?
    public let deleteCardIDs: [String]?

    public init(
        kind: DockStreamKind,
        schemaVersion: Int? = nil,
        view: ThreadCardStreamView? = nil,
        complete: Bool? = nil,
        totalRows: Int? = nil,
        window: DockStreamWindowDTO? = nil,
        stateGeneration: Int64? = nil,
        epoch: String,
        baseSeq: Int64? = nil,
        seq: Int64,
        asOf: String? = nil,
        freshness: DockStreamFreshnessDTO? = nil,
        hosts: [DockStreamHostDTO]? = nil,
        cards: [DockThreadCardDTO]? = nil,
        upsertHosts: [DockStreamHostDTO]? = nil,
        upsertCards: [DockThreadCardDTO]? = nil,
        deleteCardIDs: [String]? = nil
    ) {
        self.kind = kind
        self.schemaVersion = schemaVersion
        self.view = view
        self.complete = complete
        self.totalRows = totalRows
        self.window = window
        self.stateGeneration = stateGeneration
        self.epoch = epoch
        self.baseSeq = baseSeq
        self.seq = seq
        self.asOf = asOf
        self.freshness = freshness
        self.hosts = hosts
        self.cards = cards
        self.upsertHosts = upsertHosts
        self.upsertCards = upsertCards
        self.deleteCardIDs = deleteCardIDs
    }
}
